server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jca412345/springcloud-config.git
          username: jca412345
          password: jca4123
          #default-label: main
          ####搜索目录
          search-paths:
            - springcloud-config
      label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka