server:
  port: 3344
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jca412345/springcloud-config.git
#          username: jca412345
#          password: jca4123
          search-paths: config
          default-label: main

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka